import {
  mobile,
  backend,
  creator,
  web,
  javascript,
  typescript,
  html,
  css,
  reactjs,
  redux,
  tailwind,
  nodejs,
  mongodb,
  git,
  figma,
  docker,
  meta,
  starbucks,
  tesla,
  shopify,
  carrent,
  jobit,
  tripguide,
  threejs,
  logo1,
  logo2,
  logo4,
  logo5,
} from "../assets";

const experiences = [
  {
    title: "Technical Faculty",
    company_name: "Jetking Institue",
    icon: logo5,
    iconBg: "#383E56",
    date: "March 2020 - April 2021",
    points: [
      "Taught web applications using React.js and other related technologies.",
      "Collaboration wok shops with cross-functional teams including designers, product managers, and other developers to create high-quality teaching.",
      "Teaching responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback with the students.",
      "Delivered training on front-end development",
      "Mentored students through 10+ academic projects",
    ],
  },
  {
    title: "Technology Associate",
    company_name: "Cornelia Chambers",
    icon: logo2,
    iconBg: "#E6DEDD",
    date: "March 2022 - February 2023",
    points: [
        "Built cross-platform mobile apps using React, integrating with Appwrite's backend services.",
        "Improved web app performance and user experience through code optimization and testing.",
        "Coordinated with the product team to implement features based on feedback.",
        "Designed and implemented responsive UI for B2B platforms in React.",
        "Collaborated on No Grey platform – created wireframes and functional layouts.",
      ],
  },
  {
    title: "IT L2 Engineer",
    company_name: "Air India",
    icon: logo4,
    iconBg: "#383E56",
    date: "June 2023 - Jul 2024",
    points: [
      "Led the development of Network applications, focusing on scalability.",
        "Worked with Network engineers to integrate Cisco Routers for seamlessly work flow with the sytems on the network.",
        "Implemented departmental network interfaces and cloud solutions.",
        "Upgraded network infrastructure and maintained protocols.",
    ],
  },
  {
    title: "Software Developer | Project Manger",
    company_name: "Contract Projects",
    icon: logo1,
    iconBg: "#E6DEDD",
    date: "Aug 2024 - Present",
    points: [
      "Developed and maintained user-facing features for the Hostinger website.",
        "Collaborated closely with UI/UX designers to ensure seamless user experiences.",
        "Led development of 25+ front-end projects using React, Next.js, and Tailwind CSS.",
        "Integrated secure APIs and managed project life cycle.",
        "Optimized web applications for maximum speed and scalability.",
    ],
  },
];


export { experiences};