export const serviceDetails = [
  {
    slug: "landing-page-development",
    title: "Landing Page Development",
    eyebrow: "Conversion-focused web experiences",
    overview: "A focused landing page designed to communicate your offer clearly, build trust quickly, and turn qualified visitors into conversations.",
    included: ["Conversion-focused page structure", "Responsive implementation", "Clear calls to action", "Performance and accessibility basics"],
    technologies: ["React", "Next.js", "Tailwind CSS", "Framer Motion"],
    timeline: "1–2 weeks",
    seoTitle: "Landing Page Development Services",
    seoDescription: "Conversion-focused landing page development for startups and businesses that need a fast, credible way to turn traffic into qualified leads.",
    keywords: ["landing page development", "conversion landing page", "React landing page developer"],
    faqs: [
      { question: "Can you work from an existing design?", answer: "Yes. I can implement an existing design system or help shape a focused page using your current brand direction." },
      { question: "Will the page work on mobile?", answer: "Yes. Every landing page is built responsively and tested across common screen sizes." },
    ],
  },
  {
    slug: "business-website-development",
    title: "Business Website Development",
    eyebrow: "A credible home for your business",
    overview: "A professional multi-page website that explains what you do, supports your sales process, and gives prospects confidence in your business.",
    included: ["Core marketing pages", "Responsive navigation", "Contact conversion paths", "Maintainable component structure"],
    technologies: ["React", "Next.js", "Tailwind CSS", "SEO-ready markup"],
    timeline: "2–4 weeks",
    seoTitle: "Business Website Development Services",
    seoDescription: "Professional business website development with responsive React and Next.js builds designed for trust, discoverability, and conversion.",
    keywords: ["business website development", "professional website developer", "React business website"],
    faqs: [
      { question: "Can the website grow with new pages?", answer: "Yes. The build uses reusable sections and a maintainable structure so new content and pages can be added cleanly." },
      { question: "Do you handle the contact form?", answer: "I can connect the existing contact flow or integrate the form requirements defined for the project." },
    ],
  },
  {
    slug: "backend-api-development",
    title: "Backend & API Development",
    eyebrow: "Secure systems behind your product",
    overview: "Reliable backend services and APIs that connect your product, data, automations, and third-party tools without creating fragile workflows.",
    included: ["API design and implementation", "Database integration", "Authentication-ready architecture", "Third-party service integration"],
    technologies: ["Node.js", "Express", "REST APIs", "MongoDB"],
    timeline: "2–5 weeks",
    seoTitle: "Backend and API Development Services",
    seoDescription: "Secure Node.js backend and API development for product teams that need reliable data flows, integrations, and scalable foundations.",
    keywords: ["backend API development", "Node.js backend developer", "REST API development"],
    faqs: [
      { question: "Can you integrate an existing API?", answer: "Yes. I can connect, extend, or stabilize existing APIs and third-party services as part of the scope." },
      { question: "How do you approach security?", answer: "The scope includes secure data handling, validation, and access-control considerations appropriate to the product." },
    ],
  },
  {
    slug: "business-dashboard-development",
    title: "Business Dashboard Development",
    eyebrow: "Operational clarity for your team",
    overview: "Custom internal dashboards that turn scattered operational data into clear, useful workflows for the people running your business.",
    included: ["Role-based dashboard views", "Data and API integration", "Responsive interface design", "Reusable reporting components"],
    technologies: ["React", "Node.js", "Charts", "REST APIs"],
    timeline: "3–6 weeks",
    seoTitle: "Business Dashboard Development Services",
    seoDescription: "Custom business dashboard development for teams that need streamlined workflows, connected data, and actionable operational visibility.",
    keywords: ["business dashboard development", "internal tool development", "custom admin dashboard"],
    faqs: [
      { question: "Can the dashboard connect to our current tools?", answer: "Yes. The project can include integrations with the APIs, databases, or spreadsheets your team already uses." },
      { question: "Can different users see different information?", answer: "Yes. Role-based access can be planned where the product requires it." },
    ],
  },
  {
    slug: "custom-web-application",
    title: "Custom Web Application Development",
    eyebrow: "Software shaped around your workflow",
    overview: "A tailored web application for a specific product idea, customer journey, or internal workflow that off-the-shelf tools cannot support well.",
    included: ["Product-focused technical planning", "Responsive application interface", "Backend and data foundation", "Milestone-based delivery"],
    technologies: ["React", "Next.js", "Node.js", "MongoDB"],
    timeline: "4–10 weeks",
    seoTitle: "Custom Web Application Development",
    seoDescription: "Custom web application development for businesses that need scalable React, Next.js, and Node.js software built around their workflow.",
    keywords: ["custom web application development", "React web app developer", "custom software development"],
    faqs: [
      { question: "Can you help define the first version?", answer: "Yes. Discovery focuses on the smallest useful release so you can validate the product before expanding scope." },
      { question: "Will I be able to add features later?", answer: "Yes. The application is structured for maintainability so future features do not require a rewrite." },
    ],
  },
  {
    slug: "ai-automation",
    title: "AI Automation Development",
    eyebrow: "Reduce repetitive work responsibly",
    overview: "Practical AI automations that connect your existing tools, reduce manual operations, and keep people in control of important decisions.",
    included: ["Workflow discovery", "AI and API integration", "Human-review checkpoints", "Monitoring-ready implementation"],
    technologies: ["LLM APIs", "Node.js", "Webhooks", "Automation APIs"],
    timeline: "2–5 weeks",
    seoTitle: "AI Automation Development Services",
    seoDescription: "AI automation development for businesses that want to connect tools, reduce repetitive work, and build dependable workflow automations.",
    keywords: ["AI automation", "business automation", "workflow automation development"],
    faqs: [
      { question: "Which workflows are good candidates for automation?", answer: "Repeatable, high-volume tasks with clear inputs and review rules are usually the strongest starting point." },
      { question: "Will AI replace our existing process immediately?", answer: "No. Automations are introduced with appropriate controls and can keep human review at important decision points." },
    ],
  },
  {
    slug: "ai-web-application",
    title: "AI Web Application Development",
    eyebrow: "AI features people can actually use",
    overview: "Customer-facing web applications that use AI to improve search, analysis, support, content workflows, or data-driven experiences.",
    included: ["AI feature planning", "Web application interface", "Secure model/API integration", "Usage and error-state handling"],
    technologies: ["React", "Next.js", "LLM APIs", "Node.js"],
    timeline: "4–8 weeks",
    seoTitle: "AI Web Application Development Services",
    seoDescription: "AI web application development using React, Next.js, Node.js, and LLM integrations for useful, scalable customer experiences.",
    keywords: ["AI web application development", "LLM web app", "AI product engineer"],
    faqs: [
      { question: "Can you integrate a specific AI provider?", answer: "Yes. Provider selection is based on the product requirements, reliability, data handling, and cost profile." },
      { question: "How do you manage unreliable AI responses?", answer: "The product is designed with clear states, validation, fallbacks, and user feedback paths rather than treating model output as guaranteed." },
    ],
  },
  {
    slug: "ai-chatbot-development",
    title: "AI Chatbot Development",
    eyebrow: "Helpful conversations at scale",
    overview: "AI chatbots that answer common questions, guide users through workflows, and connect to the knowledge and systems your team already trusts.",
    included: ["Conversation-flow planning", "Knowledge-source integration", "Chat interface implementation", "Escalation and fallback design"],
    technologies: ["LLM APIs", "React", "Node.js", "Vector search"],
    timeline: "3–6 weeks",
    seoTitle: "AI Chatbot Development Services",
    seoDescription: "AI chatbot development for support, internal knowledge, and customer workflows with secure LLM integration and thoughtful escalation paths.",
    keywords: ["AI chatbot development", "custom chatbot", "LLM chatbot development"],
    faqs: [
      { question: "Can the chatbot use our internal documents?", answer: "Yes. A scoped knowledge integration can be added so answers are grounded in approved business information." },
      { question: "Can a human take over the conversation?", answer: "Yes. Escalation paths can be designed for cases that require human support or approval." },
    ],
  },
  {
    slug: "saas-mvp-development",
    title: "SaaS MVP Development",
    eyebrow: "Launch the right first version",
    overview: "A focused SaaS MVP that helps you validate demand, learn from real users, and build a technical foundation for the next stage of your product.",
    included: ["MVP scope and milestone planning", "Core user flows", "Authentication-ready setup", "Scalable application architecture"],
    technologies: ["Next.js", "React", "Node.js", "Database APIs"],
    timeline: "6–12 weeks",
    seoTitle: "SaaS MVP Development Services",
    seoDescription: "SaaS MVP development for founders who need a focused, scalable first product built with React, Next.js, Node.js, and modern APIs.",
    keywords: ["SaaS MVP development", "MVP developer", "startup web application development"],
    faqs: [
      { question: "Can you help prioritise MVP features?", answer: "Yes. The first step is identifying the core user problem and the smallest set of flows needed to test it." },
      { question: "Is the MVP built for future growth?", answer: "Yes. The goal is a focused first release with a maintainable foundation, not a disposable prototype." },
    ],
  },
];

export const getServiceDetail = (slug) =>
  serviceDetails.find((service) => service.slug === slug);
